"""Add donor_email column to blood_request

Revision ID: 23052c03629a
Revises: 
Create Date: 2025-03-12 21:34:50.331827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23052c03629a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_request', schema=None) as batch_op:
        batch_op.drop_column('donor_email')

    # ### end Alembic commands ###
