"""Add recipient_id to Donation model with named constraints

Revision ID: 387af6a48133
Revises: 23052c03629a
Create Date: 2025-03-18 10:31:23.203977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387af6a48133'
down_revision = '23052c03629a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_donation_recipient_id', 'user', ['recipient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donation_recipient_id', type_='foreignkey')
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###
